### Patikrinti pagr puslapi
GET http://localhost:3002/


### Patikrinti rysi su DB
GET http://localhost:3002/test-connection


### Get all advertisements
GET http://localhost:3002/api/advertisement


### Get single advertisement
GET http://localhost:3002/api/advertisement/1

### Update single advertisement
PUT http://localhost:3002/api/advertisement/1
Content-Type: application/json

{
  "title": "Dviratis",
  "price": "120",
  "text": "Kalnu dviratis"
}

### DELETE single advertisement
DELETE http://localhost:3002/api/advertisement/5

### POST Register User
POST http://localhost:3002/api/auth/register
Content-Type: application/json

{
  "email": "e.jurgelevicius@gmail.com",
  "password": "123456"
}


### POST Login User
POST http://localhost:3002/api/auth/login
Content-Type: application/json

{
  "email": "e.jurgelevicius@gmail.com",
  "password": "123456"
}

